[0m17:09:31.061894 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2d1f371960>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2d1e88b580>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2d1e888310>]}


============================== 17:09:31.070617 | 4a5ee0e8-7572-46ac-93ab-0074a354f20f ==============================
[0m17:09:31.070617 [info ] [MainThread]: Running with dbt=1.9.2
[0m17:09:31.072299 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/app/dbt_project', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt debug', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m17:09:31.085591 [info ] [MainThread]: dbt version: 1.9.2
[0m17:09:31.087074 [info ] [MainThread]: python version: 3.10.16
[0m17:09:31.088097 [info ] [MainThread]: python path: /usr/local/bin/python3.10
[0m17:09:31.089072 [info ] [MainThread]: os info: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[0m17:09:31.094080 [error] [MainThread]: Encountered an error:
local variable 'summary_message' referenced before assignment
[0m17:09:31.095368 [error] [MainThread]: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/dbt/cli/requires.py", line 153, in wrapper
    result, success = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/dbt/cli/requires.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/dbt/cli/main.py", line 414, in debug
    results = task.run()
  File "/usr/local/lib/python3.10/site-packages/dbt/task/debug.py", line 114, in run
    load_profile_status: SubtaskStatus = self._load_profile()
  File "/usr/local/lib/python3.10/site-packages/dbt/task/debug.py", line 201, in _load_profile
    profile_names, summary_message = self._choose_profile_names()
  File "/usr/local/lib/python3.10/site-packages/dbt/task/debug.py", line 276, in _choose_profile_names
    return profiles, summary_message
UnboundLocalError: local variable 'summary_message' referenced before assignment

[0m17:09:31.097748 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_success": false, "command_wall_clock_time": 0.053147398, "process_in_blocks": "1808", "process_kernel_time": 0.45758, "process_mem_max_rss": "86436", "process_out_blocks": "1040", "process_user_time": 1.153899}
[0m17:09:31.098710 [debug] [MainThread]: Command `dbt debug` failed at 17:09:31.098537 after 0.05 seconds
[0m17:09:31.099529 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2d1f371960>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2d20249810>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2d1e374610>]}
[0m17:09:31.100201 [debug] [MainThread]: Flushing usage events
[0m17:09:31.898107 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m17:14:24.091888 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2123eed960>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2123407580>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2123404340>]}


============================== 17:14:24.104853 | 4e82bf7f-6ab9-4125-9a10-25ba3b8cb740 ==============================
[0m17:14:24.104853 [info ] [MainThread]: Running with dbt=1.9.2
[0m17:14:24.106440 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': '/app/dbt_project', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt debug', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m17:14:24.129715 [info ] [MainThread]: dbt version: 1.9.2
[0m17:14:24.131985 [info ] [MainThread]: python version: 3.10.16
[0m17:14:24.133078 [info ] [MainThread]: python path: /usr/local/bin/python3.10
[0m17:14:24.134263 [info ] [MainThread]: os info: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[0m17:14:24.145026 [error] [MainThread]: Encountered an error:
local variable 'summary_message' referenced before assignment
[0m17:14:24.147934 [error] [MainThread]: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/dbt/cli/requires.py", line 153, in wrapper
    result, success = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/dbt/cli/requires.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/dbt/cli/main.py", line 414, in debug
    results = task.run()
  File "/usr/local/lib/python3.10/site-packages/dbt/task/debug.py", line 114, in run
    load_profile_status: SubtaskStatus = self._load_profile()
  File "/usr/local/lib/python3.10/site-packages/dbt/task/debug.py", line 201, in _load_profile
    profile_names, summary_message = self._choose_profile_names()
  File "/usr/local/lib/python3.10/site-packages/dbt/task/debug.py", line 276, in _choose_profile_names
    return profiles, summary_message
UnboundLocalError: local variable 'summary_message' referenced before assignment

[0m17:14:24.150966 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_success": false, "command_wall_clock_time": 0.07825231, "process_in_blocks": "1640", "process_kernel_time": 0.708205, "process_mem_max_rss": "86484", "process_out_blocks": "1040", "process_user_time": 1.325355}
[0m17:14:24.152179 [debug] [MainThread]: Command `dbt debug` failed at 17:14:24.152031 after 0.08 seconds
[0m17:14:24.153139 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2123eed960>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2124dc1a20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2122eec610>]}
[0m17:14:24.154182 [debug] [MainThread]: Flushing usage events
[0m17:14:24.939466 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m17:27:11.111066 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fefecf9d600>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fefeddcf970>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fefeddcf910>]}


============================== 17:27:11.121724 | 0faf78e5-c188-4f9c-9f68-8066c639c854 ==============================
[0m17:27:11.121724 [info ] [MainThread]: Running with dbt=1.9.2
[0m17:27:11.123010 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/app/dbt_project', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt debug', 'send_anonymous_usage_stats': 'True'}
[0m17:27:11.149395 [info ] [MainThread]: dbt version: 1.9.2
[0m17:27:11.150656 [info ] [MainThread]: python version: 3.10.16
[0m17:27:11.151662 [info ] [MainThread]: python path: /usr/local/bin/python3.10
[0m17:27:11.152630 [info ] [MainThread]: os info: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[0m17:27:11.157431 [error] [MainThread]: Encountered an error:
local variable 'summary_message' referenced before assignment
[0m17:27:11.163500 [error] [MainThread]: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/dbt/cli/requires.py", line 153, in wrapper
    result, success = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/dbt/cli/requires.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/dbt/cli/main.py", line 414, in debug
    results = task.run()
  File "/usr/local/lib/python3.10/site-packages/dbt/task/debug.py", line 114, in run
    load_profile_status: SubtaskStatus = self._load_profile()
  File "/usr/local/lib/python3.10/site-packages/dbt/task/debug.py", line 201, in _load_profile
    profile_names, summary_message = self._choose_profile_names()
  File "/usr/local/lib/python3.10/site-packages/dbt/task/debug.py", line 276, in _choose_profile_names
    return profiles, summary_message
UnboundLocalError: local variable 'summary_message' referenced before assignment

[0m17:27:11.166963 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_success": false, "command_wall_clock_time": 0.0724187, "process_in_blocks": "4288", "process_kernel_time": 1.042113, "process_mem_max_rss": "84996", "process_out_blocks": "0", "process_user_time": 1.151287}
[0m17:27:11.167861 [debug] [MainThread]: Command `dbt debug` failed at 17:27:11.167691 after 0.07 seconds
[0m17:27:11.168727 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fefecf9d600>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fefeddcf8b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fefede77d00>]}
[0m17:27:11.169807 [debug] [MainThread]: Flushing usage events
[0m17:27:11.922353 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m14:39:56.211036 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000234676410D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023467641210>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023467643450>]}


============================== 14:39:56.217036 | eabd3a3b-d322-4261-b37e-45878716f2f7 ==============================
[0m14:39:56.217036 [info ] [MainThread]: Running with dbt=1.9.2
[0m14:39:56.218037 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\henrique.soares\\.dbt', 'log_path': 'C:\\Users\\henrique.soares\\Desktop\\DataGlowUp\\logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt debug', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m14:39:56.237038 [info ] [MainThread]: dbt version: 1.9.2
[0m14:39:56.238040 [info ] [MainThread]: python version: 3.11.9
[0m14:39:56.239038 [info ] [MainThread]: python path: C:\Users\henrique.soares\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe
[0m14:39:56.239038 [info ] [MainThread]: os info: Windows-10-10.0.26100-SP0
[0m14:39:56.243065 [info ] [MainThread]: Using profiles dir at C:\Users\henrique.soares\.dbt
[0m14:39:56.244042 [info ] [MainThread]: Using profiles.yml file at C:\Users\henrique.soares\.dbt\profiles.yml
[0m14:39:56.244042 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\henrique.soares\Desktop\DataGlowUp\dbt_project.yml
[0m14:39:56.323675 [info ] [MainThread]: Configuration:
[0m14:39:56.324675 [info ] [MainThread]:   profiles.yml file [[31mERROR invalid[0m]
[0m14:39:56.325678 [info ] [MainThread]:   dbt_project.yml file [[32mOK found and valid[0m]
[0m14:39:56.326676 [info ] [MainThread]: Required dependencies:
[0m14:39:56.326676 [debug] [MainThread]: Executing "git --help"
[0m14:39:56.373205 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--no-lazy-fetch]\n           [--no-optional-locks] [--no-advice] [--bare] [--git-dir=<path>]\n           [--work-tree=<path>] [--namespace=<name>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone      Clone a repository into a new directory\n   init       Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add        Add file contents to the index\n   mv         Move or rename a file, a directory, or a symlink\n   restore    Restore working tree files\n   rm         Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect     Use binary search to find the commit that introduced a bug\n   diff       Show changes between commits, commit and working tree, etc\n   grep       Print lines matching a pattern\n   log        Show commit logs\n   show       Show various types of objects\n   status     Show the working tree status\n\ngrow, mark and tweak your common history\n   backfill   Download missing objects in a partial clone\n   branch     List, create, or delete branches\n   commit     Record changes to the repository\n   merge      Join two or more development histories together\n   rebase     Reapply commits on top of another base tip\n   reset      Reset current HEAD to the specified state\n   switch     Switch branches\n   tag        Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch      Download objects and refs from another repository\n   pull       Fetch from and integrate with another repository or a local branch\n   push       Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m14:39:56.374204 [debug] [MainThread]: STDERR: "b''"
[0m14:39:56.375203 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m14:39:56.375203 [info ] [MainThread]: Connection test skipped since no profile was found
[0m14:39:56.376202 [info ] [MainThread]: [31m1 check failed:[0m
[0m14:39:56.377205 [info ] [MainThread]: Profile loading failed for the following reason:
Runtime Error
  Could not find profile named 'default'


[0m14:39:56.378203 [debug] [MainThread]: Command `dbt debug` failed at 14:39:56.378203 after 0.23 seconds
[0m14:39:56.378203 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023461AFEA50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023461B7B890>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000234673681D0>]}
[0m14:39:56.379203 [debug] [MainThread]: Flushing usage events
[0m14:39:57.115369 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m14:53:48.037737 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019CDCC41E50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019CDCC3BE90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019CDCC3B450>]}


============================== 14:53:48.042754 | 5c27b6b8-1e83-4bbd-a0a6-9aa2aa60eae9 ==============================
[0m14:53:48.042754 [info ] [MainThread]: Running with dbt=1.9.2
[0m14:53:48.043737 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\henrique.soares\\.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'C:\\Users\\henrique.soares\\Desktop\\DataGlowUp\\logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m14:53:48.046755 [error] [MainThread]: Encountered an error:
Runtime Error
  Could not find profile named 'default'
[0m14:53:48.048305 [debug] [MainThread]: Command `dbt run` failed at 14:53:48.047291 after 0.08 seconds
[0m14:53:48.048305 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019CD804AA50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019CDCC983D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019CD80CB890>]}
[0m14:53:48.048305 [debug] [MainThread]: Flushing usage events
[0m14:53:48.823522 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m14:54:01.335947 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F04DA42110>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F04DA39050>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F04DA3B110>]}


============================== 14:54:01.340076 | 3e5a212e-1b6a-441a-ad39-3571449c6f0b ==============================
[0m14:54:01.340076 [info ] [MainThread]: Running with dbt=1.9.2
[0m14:54:01.341056 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\henrique.soares\\.dbt', 'log_path': 'C:\\Users\\henrique.soares\\Desktop\\DataGlowUp\\logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m14:54:01.344044 [error] [MainThread]: Encountered an error:
Runtime Error
  Could not find profile named 'default'
[0m14:54:01.344948 [debug] [MainThread]: Command `dbt run` failed at 14:54:01.344948 after 0.07 seconds
[0m14:54:01.344948 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F04D737310>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F048EAAA50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F04D583F90>]}
[0m14:54:01.345983 [debug] [MainThread]: Flushing usage events
[0m14:54:02.061080 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m14:54:55.629124 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E562066310>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E56208DED0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E56208D9D0>]}


============================== 14:54:55.636125 | 21a8541a-b768-49a0-90e5-ee66c020dead ==============================
[0m14:54:55.636125 [info ] [MainThread]: Running with dbt=1.9.2
[0m14:54:55.637125 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\henrique.soares\\Desktop\\DataGlowUp', 'version_check': 'True', 'debug': 'False', 'log_path': 'C:\\Users\\henrique.soares\\Desktop\\DataGlowUp\\logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt run', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m14:54:55.835925 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': '21a8541a-b768-49a0-90e5-ee66c020dead', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E56224D5D0>]}
[0m14:54:55.876429 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': '21a8541a-b768-49a0-90e5-ee66c020dead', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E55E2DC250>]}
[0m14:54:55.878430 [info ] [MainThread]: Registered adapter: postgres=1.9.0
[0m14:54:56.122560 [debug] [MainThread]: checksum: 12b12750b70de726cfd89136b8e24afc3f3e77597a97bff40ab7e5f9b39d5e18, vars: {}, profile: , target: , version: 1.9.2
[0m14:54:56.122560 [info ] [MainThread]: Unable to do partial parsing because saved manifest not found. Starting full parse.
[0m14:54:56.123569 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'partial_parser', 'label': '21a8541a-b768-49a0-90e5-ee66c020dead', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E5621EF690>]}
[0m14:54:56.719920 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': '21a8541a-b768-49a0-90e5-ee66c020dead', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E5624E5310>]}
[0m14:54:56.753183 [debug] [MainThread]: Wrote artifact WritableManifest to C:\Users\henrique.soares\Desktop\DataGlowUp\target\manifest.json
[0m14:54:56.757627 [debug] [MainThread]: Wrote artifact SemanticManifest to C:\Users\henrique.soares\Desktop\DataGlowUp\target\semantic_manifest.json
[0m14:54:56.786940 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': '21a8541a-b768-49a0-90e5-ee66c020dead', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E56280EC90>]}
[0m14:54:56.787964 [info ] [MainThread]: Found 1 model, 433 macros
[0m14:54:56.787964 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': '21a8541a-b768-49a0-90e5-ee66c020dead', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E5626CD790>]}
[0m14:54:56.789967 [info ] [MainThread]: 
[0m14:54:56.789967 [info ] [MainThread]: Concurrency: 1 threads (target='dev')
[0m14:54:56.790940 [info ] [MainThread]: 
[0m14:54:56.790940 [debug] [MainThread]: Acquiring new postgres connection 'master'
[0m14:54:56.792939 [debug] [ThreadPool]: Acquiring new postgres connection 'list_mydatabase'
[0m14:54:59.131316 [debug] [ThreadPool]: Using postgres connection "list_mydatabase"
[0m14:54:59.131316 [debug] [ThreadPool]: On list_mydatabase: /* {"app": "dbt", "dbt_version": "1.9.2", "profile_name": "default", "target_name": "dev", "connection_name": "list_mydatabase"} */

    select distinct nspname from pg_namespace
  
[0m14:54:59.132314 [debug] [ThreadPool]: Opening a new connection, currently in state init
[0m14:54:59.288563 [debug] [ThreadPool]: SQL status: SELECT 4 in 0.157 seconds
[0m14:54:59.289566 [debug] [ThreadPool]: On list_mydatabase: Close
[0m14:54:59.292564 [debug] [ThreadPool]: Acquiring new postgres connection 'list_mydatabase_public'
[0m14:54:59.296563 [debug] [ThreadPool]: Using postgres connection "list_mydatabase_public"
[0m14:54:59.297563 [debug] [ThreadPool]: On list_mydatabase_public: BEGIN
[0m14:54:59.297563 [debug] [ThreadPool]: Opening a new connection, currently in state init
[0m14:54:59.315563 [debug] [ThreadPool]: SQL status: BEGIN in 0.018 seconds
[0m14:54:59.315563 [debug] [ThreadPool]: Using postgres connection "list_mydatabase_public"
[0m14:54:59.316563 [debug] [ThreadPool]: On list_mydatabase_public: /* {"app": "dbt", "dbt_version": "1.9.2", "profile_name": "default", "target_name": "dev", "connection_name": "list_mydatabase_public"} */
select
      'mydatabase' as database,
      tablename as name,
      schemaname as schema,
      'table' as type
    from pg_tables
    where schemaname ilike 'public'
    union all
    select
      'mydatabase' as database,
      viewname as name,
      schemaname as schema,
      'view' as type
    from pg_views
    where schemaname ilike 'public'
    union all
    select
      'mydatabase' as database,
      matviewname as name,
      schemaname as schema,
      'materialized_view' as type
    from pg_matviews
    where schemaname ilike 'public'
  
[0m14:54:59.359431 [debug] [ThreadPool]: SQL status: SELECT 2 in 0.043 seconds
[0m14:54:59.361434 [debug] [ThreadPool]: On list_mydatabase_public: ROLLBACK
[0m14:54:59.362431 [debug] [ThreadPool]: On list_mydatabase_public: Close
[0m14:54:59.366944 [debug] [MainThread]: Using postgres connection "master"
[0m14:54:59.367943 [debug] [MainThread]: On master: BEGIN
[0m14:54:59.367943 [debug] [MainThread]: Opening a new connection, currently in state init
[0m14:54:59.390304 [debug] [MainThread]: SQL status: BEGIN in 0.022 seconds
[0m14:54:59.390890 [debug] [MainThread]: Using postgres connection "master"
[0m14:54:59.390890 [debug] [MainThread]: On master: /* {"app": "dbt", "dbt_version": "1.9.2", "profile_name": "default", "target_name": "dev", "connection_name": "master"} */
with relation as (
        select
            pg_rewrite.ev_class as class,
            pg_rewrite.oid as id
        from pg_rewrite
    ),
    class as (
        select
            oid as id,
            relname as name,
            relnamespace as schema,
            relkind as kind
        from pg_class
    ),
    dependency as (
        select distinct
            pg_depend.objid as id,
            pg_depend.refobjid as ref
        from pg_depend
    ),
    schema as (
        select
            pg_namespace.oid as id,
            pg_namespace.nspname as name
        from pg_namespace
        where nspname != 'information_schema' and nspname not like 'pg\_%'
    ),
    referenced as (
        select
            relation.id AS id,
            referenced_class.name ,
            referenced_class.schema ,
            referenced_class.kind
        from relation
        join class as referenced_class on relation.class=referenced_class.id
        where referenced_class.kind in ('r', 'v', 'm')
    ),
    relationships as (
        select
            referenced.name as referenced_name,
            referenced.schema as referenced_schema_id,
            dependent_class.name as dependent_name,
            dependent_class.schema as dependent_schema_id,
            referenced.kind as kind
        from referenced
        join dependency on referenced.id=dependency.id
        join class as dependent_class on dependency.ref=dependent_class.id
        where
            (referenced.name != dependent_class.name or
             referenced.schema != dependent_class.schema)
    )

    select
        referenced_schema.name as referenced_schema,
        relationships.referenced_name as referenced_name,
        dependent_schema.name as dependent_schema,
        relationships.dependent_name as dependent_name
    from relationships
    join schema as dependent_schema on relationships.dependent_schema_id=dependent_schema.id
    join schema as referenced_schema on relationships.referenced_schema_id=referenced_schema.id
    group by referenced_schema, referenced_name, dependent_schema, dependent_name
    order by referenced_schema, referenced_name, dependent_schema, dependent_name;
[0m14:54:59.424730 [debug] [MainThread]: SQL status: SELECT 0 in 0.034 seconds
[0m14:54:59.426738 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': '21a8541a-b768-49a0-90e5-ee66c020dead', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E5627799D0>]}
[0m14:54:59.426738 [debug] [MainThread]: On master: ROLLBACK
[0m14:54:59.427744 [debug] [MainThread]: Using postgres connection "master"
[0m14:54:59.428642 [debug] [MainThread]: On master: BEGIN
[0m14:54:59.430639 [debug] [MainThread]: SQL status: BEGIN in 0.002 seconds
[0m14:54:59.431525 [debug] [MainThread]: On master: COMMIT
[0m14:54:59.432033 [debug] [MainThread]: Using postgres connection "master"
[0m14:54:59.432033 [debug] [MainThread]: On master: COMMIT
[0m14:54:59.433371 [debug] [MainThread]: SQL status: COMMIT in 0.001 seconds
[0m14:54:59.433965 [debug] [MainThread]: On master: Close
[0m14:54:59.436527 [debug] [Thread-1 (]: Began running node model.my_dbt_project.raw.data
[0m14:54:59.437200 [info ] [Thread-1 (]: 1 of 1 START sql table model public.raw.data ................................... [RUN]
[0m14:54:59.438503 [debug] [Thread-1 (]: Acquiring new postgres connection 'model.my_dbt_project.raw.data'
[0m14:54:59.439046 [debug] [Thread-1 (]: Began compiling node model.my_dbt_project.raw.data
[0m14:54:59.443553 [debug] [Thread-1 (]: Writing injected SQL for node "model.my_dbt_project.raw.data"
[0m14:54:59.445201 [debug] [Thread-1 (]: Began executing node model.my_dbt_project.raw.data
[0m14:54:59.478365 [debug] [Thread-1 (]: Writing runtime sql for node "model.my_dbt_project.raw.data"
[0m14:54:59.480364 [debug] [Thread-1 (]: Using postgres connection "model.my_dbt_project.raw.data"
[0m14:54:59.480364 [debug] [Thread-1 (]: On model.my_dbt_project.raw.data: BEGIN
[0m14:54:59.480364 [debug] [Thread-1 (]: Opening a new connection, currently in state init
[0m14:54:59.492365 [debug] [Thread-1 (]: SQL status: BEGIN in 0.012 seconds
[0m14:54:59.493498 [debug] [Thread-1 (]: Using postgres connection "model.my_dbt_project.raw.data"
[0m14:54:59.493498 [debug] [Thread-1 (]: On model.my_dbt_project.raw.data: /* {"app": "dbt", "dbt_version": "1.9.2", "profile_name": "default", "target_name": "dev", "node_id": "model.my_dbt_project.raw.data"} */

  
    

  create  table "mydatabase"."public"."raw.data__dbt_tmp"
  
  
    as
  
  (
    -- Modelo simples para visualizar dados brutos
select * from public
  );
  
[0m14:54:59.496495 [debug] [Thread-1 (]: Postgres adapter: Postgres error: relation "public" does not exist
LINE 13: select * from public
                       ^

[0m14:54:59.497499 [debug] [Thread-1 (]: On model.my_dbt_project.raw.data: ROLLBACK
[0m14:54:59.498493 [debug] [Thread-1 (]: On model.my_dbt_project.raw.data: Close
[0m14:54:59.626293 [debug] [Thread-1 (]: Database Error in model raw.data (C:/Users/henrique.soares/Desktop/DataGlowUp/models\raw.data.sql)
  relation "public" does not exist
  LINE 13: select * from public
                         ^
  compiled code at C:/Users/henrique.soares/Desktop/DataGlowUp/models\raw.data.sql
[0m14:54:59.633630 [debug] [Thread-1 (]: Sending event: {'category': 'dbt', 'action': 'run_model', 'label': '21a8541a-b768-49a0-90e5-ee66c020dead', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E562696B10>]}
[0m14:54:59.634135 [error] [Thread-1 (]: 1 of 1 ERROR creating sql table model public.raw.data .......................... [[31mERROR[0m in 0.19s]
[0m14:54:59.635561 [debug] [Thread-1 (]: Finished running node model.my_dbt_project.raw.data
[0m14:54:59.635561 [debug] [Thread-4 (]: Marking all children of 'model.my_dbt_project.raw.data' to be skipped because of status 'error'.  Reason: Database Error in model raw.data (C:/Users/henrique.soares/Desktop/DataGlowUp/models\raw.data.sql)
  relation "public" does not exist
  LINE 13: select * from public
                         ^
  compiled code at C:/Users/henrique.soares/Desktop/DataGlowUp/models\raw.data.sql.
[0m14:54:59.637566 [debug] [MainThread]: Using postgres connection "master"
[0m14:54:59.638225 [debug] [MainThread]: On master: BEGIN
[0m14:54:59.638225 [debug] [MainThread]: Opening a new connection, currently in state closed
[0m14:54:59.648893 [debug] [MainThread]: SQL status: BEGIN in 0.010 seconds
[0m14:54:59.648893 [debug] [MainThread]: On master: COMMIT
[0m14:54:59.649659 [debug] [MainThread]: Using postgres connection "master"
[0m14:54:59.649659 [debug] [MainThread]: On master: COMMIT
[0m14:54:59.651381 [debug] [MainThread]: SQL status: COMMIT in 0.001 seconds
[0m14:54:59.651381 [debug] [MainThread]: On master: Close
[0m14:54:59.652480 [debug] [MainThread]: Connection 'master' was properly closed.
[0m14:54:59.653034 [debug] [MainThread]: Connection 'list_mydatabase' was properly closed.
[0m14:54:59.653565 [debug] [MainThread]: Connection 'list_mydatabase_public' was properly closed.
[0m14:54:59.653565 [debug] [MainThread]: Connection 'model.my_dbt_project.raw.data' was properly closed.
[0m14:54:59.654127 [info ] [MainThread]: 
[0m14:54:59.654691 [info ] [MainThread]: Finished running 1 table model in 0 hours 0 minutes and 2.86 seconds (2.86s).
[0m14:54:59.655696 [debug] [MainThread]: Command end result
[0m14:54:59.671204 [debug] [MainThread]: Wrote artifact WritableManifest to C:\Users\henrique.soares\Desktop\DataGlowUp\target\manifest.json
[0m14:54:59.674206 [debug] [MainThread]: Wrote artifact SemanticManifest to C:\Users\henrique.soares\Desktop\DataGlowUp\target\semantic_manifest.json
[0m14:54:59.680204 [debug] [MainThread]: Wrote artifact RunExecutionResult to C:\Users\henrique.soares\Desktop\DataGlowUp\target\run_results.json
[0m14:54:59.681205 [info ] [MainThread]: 
[0m14:54:59.681205 [info ] [MainThread]: [31mCompleted with 1 error, 0 partial successes, and 0 warnings:[0m
[0m14:54:59.682210 [info ] [MainThread]: 
[0m14:54:59.683206 [error] [MainThread]:   Database Error in model raw.data (C:/Users/henrique.soares/Desktop/DataGlowUp/models\raw.data.sql)
  relation "public" does not exist
  LINE 13: select * from public
                         ^
  compiled code at C:/Users/henrique.soares/Desktop/DataGlowUp/models\raw.data.sql
[0m14:54:59.683206 [info ] [MainThread]: 
[0m14:54:59.684205 [info ] [MainThread]: Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
[0m14:54:59.685207 [debug] [MainThread]: Command `dbt run` failed at 14:54:59.685207 after 4.11 seconds
[0m14:54:59.685207 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E560D683D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E55C54B790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E55C54B650>]}
[0m14:54:59.686207 [debug] [MainThread]: Flushing usage events
[0m14:55:00.410893 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m14:56:02.809226 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022F4988DED0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022F498676D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022F49867410>]}


============================== 14:56:02.815233 | 174ffd03-6341-42ae-8889-010442b8d046 ==============================
[0m14:56:02.815233 [info ] [MainThread]: Running with dbt=1.9.2
[0m14:56:02.816231 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'C:\\Users\\henrique.soares\\Desktop\\DataGlowUp\\logs', 'profiles_dir': 'C:\\Users\\henrique.soares\\Desktop\\DataGlowUp', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m14:56:02.965502 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': '174ffd03-6341-42ae-8889-010442b8d046', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022F499FE810>]}
[0m14:56:03.008501 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': '174ffd03-6341-42ae-8889-010442b8d046', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022F449CC110>]}
[0m14:56:03.009501 [info ] [MainThread]: Registered adapter: postgres=1.9.0
[0m14:56:03.185009 [debug] [MainThread]: checksum: 12b12750b70de726cfd89136b8e24afc3f3e77597a97bff40ab7e5f9b39d5e18, vars: {}, profile: , target: , version: 1.9.2
[0m14:56:03.283159 [debug] [MainThread]: Partial parsing enabled: 0 files deleted, 0 files added, 1 files changed.
[0m14:56:03.284161 [debug] [MainThread]: Partial parsing: updated file: my_dbt_project://C:/Users/henrique.soares/Desktop/DataGlowUp/models\raw.data.sql
[0m14:56:03.426807 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': '174ffd03-6341-42ae-8889-010442b8d046', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022F499D1D10>]}
[0m14:56:03.460315 [debug] [MainThread]: Wrote artifact WritableManifest to C:\Users\henrique.soares\Desktop\DataGlowUp\target\manifest.json
[0m14:56:03.464317 [debug] [MainThread]: Wrote artifact SemanticManifest to C:\Users\henrique.soares\Desktop\DataGlowUp\target\semantic_manifest.json
[0m14:56:03.487347 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': '174ffd03-6341-42ae-8889-010442b8d046', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022F4A03A0D0>]}
[0m14:56:03.487347 [info ] [MainThread]: Found 1 model, 433 macros
[0m14:56:03.488348 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': '174ffd03-6341-42ae-8889-010442b8d046', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022F49E91D10>]}
[0m14:56:03.489347 [info ] [MainThread]: 
[0m14:56:03.490348 [info ] [MainThread]: Concurrency: 1 threads (target='dev')
[0m14:56:03.491345 [info ] [MainThread]: 
[0m14:56:03.491345 [debug] [MainThread]: Acquiring new postgres connection 'master'
[0m14:56:03.493345 [debug] [ThreadPool]: Acquiring new postgres connection 'list_mydatabase'
[0m14:56:03.546861 [debug] [ThreadPool]: Using postgres connection "list_mydatabase"
[0m14:56:03.547896 [debug] [ThreadPool]: On list_mydatabase: /* {"app": "dbt", "dbt_version": "1.9.2", "profile_name": "default", "target_name": "dev", "connection_name": "list_mydatabase"} */

    select distinct nspname from pg_namespace
  
[0m14:56:03.547896 [debug] [ThreadPool]: Opening a new connection, currently in state init
[0m14:56:03.571408 [debug] [ThreadPool]: SQL status: SELECT 4 in 0.023 seconds
[0m14:56:03.572408 [debug] [ThreadPool]: On list_mydatabase: Close
[0m14:56:03.573408 [debug] [ThreadPool]: Acquiring new postgres connection 'list_mydatabase_public'
[0m14:56:03.578408 [debug] [ThreadPool]: Using postgres connection "list_mydatabase_public"
[0m14:56:03.578408 [debug] [ThreadPool]: On list_mydatabase_public: BEGIN
[0m14:56:03.578408 [debug] [ThreadPool]: Opening a new connection, currently in state init
[0m14:56:03.627856 [debug] [ThreadPool]: SQL status: BEGIN in 0.049 seconds
[0m14:56:03.628849 [debug] [ThreadPool]: Using postgres connection "list_mydatabase_public"
[0m14:56:03.628849 [debug] [ThreadPool]: On list_mydatabase_public: /* {"app": "dbt", "dbt_version": "1.9.2", "profile_name": "default", "target_name": "dev", "connection_name": "list_mydatabase_public"} */
select
      'mydatabase' as database,
      tablename as name,
      schemaname as schema,
      'table' as type
    from pg_tables
    where schemaname ilike 'public'
    union all
    select
      'mydatabase' as database,
      viewname as name,
      schemaname as schema,
      'view' as type
    from pg_views
    where schemaname ilike 'public'
    union all
    select
      'mydatabase' as database,
      matviewname as name,
      schemaname as schema,
      'materialized_view' as type
    from pg_matviews
    where schemaname ilike 'public'
  
[0m14:56:03.652216 [debug] [ThreadPool]: SQL status: SELECT 2 in 0.022 seconds
[0m14:56:03.655233 [debug] [ThreadPool]: On list_mydatabase_public: ROLLBACK
[0m14:56:03.657216 [debug] [ThreadPool]: On list_mydatabase_public: Close
[0m14:56:03.662242 [debug] [MainThread]: Using postgres connection "master"
[0m14:56:03.662242 [debug] [MainThread]: On master: BEGIN
[0m14:56:03.663244 [debug] [MainThread]: Opening a new connection, currently in state init
[0m14:56:03.690204 [debug] [MainThread]: SQL status: BEGIN in 0.027 seconds
[0m14:56:03.691205 [debug] [MainThread]: Using postgres connection "master"
[0m14:56:03.692203 [debug] [MainThread]: On master: /* {"app": "dbt", "dbt_version": "1.9.2", "profile_name": "default", "target_name": "dev", "connection_name": "master"} */
with relation as (
        select
            pg_rewrite.ev_class as class,
            pg_rewrite.oid as id
        from pg_rewrite
    ),
    class as (
        select
            oid as id,
            relname as name,
            relnamespace as schema,
            relkind as kind
        from pg_class
    ),
    dependency as (
        select distinct
            pg_depend.objid as id,
            pg_depend.refobjid as ref
        from pg_depend
    ),
    schema as (
        select
            pg_namespace.oid as id,
            pg_namespace.nspname as name
        from pg_namespace
        where nspname != 'information_schema' and nspname not like 'pg\_%'
    ),
    referenced as (
        select
            relation.id AS id,
            referenced_class.name ,
            referenced_class.schema ,
            referenced_class.kind
        from relation
        join class as referenced_class on relation.class=referenced_class.id
        where referenced_class.kind in ('r', 'v', 'm')
    ),
    relationships as (
        select
            referenced.name as referenced_name,
            referenced.schema as referenced_schema_id,
            dependent_class.name as dependent_name,
            dependent_class.schema as dependent_schema_id,
            referenced.kind as kind
        from referenced
        join dependency on referenced.id=dependency.id
        join class as dependent_class on dependency.ref=dependent_class.id
        where
            (referenced.name != dependent_class.name or
             referenced.schema != dependent_class.schema)
    )

    select
        referenced_schema.name as referenced_schema,
        relationships.referenced_name as referenced_name,
        dependent_schema.name as dependent_schema,
        relationships.dependent_name as dependent_name
    from relationships
    join schema as dependent_schema on relationships.dependent_schema_id=dependent_schema.id
    join schema as referenced_schema on relationships.referenced_schema_id=referenced_schema.id
    group by referenced_schema, referenced_name, dependent_schema, dependent_name
    order by referenced_schema, referenced_name, dependent_schema, dependent_name;
[0m14:56:03.710261 [debug] [MainThread]: SQL status: SELECT 0 in 0.017 seconds
[0m14:56:03.711261 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': '174ffd03-6341-42ae-8889-010442b8d046', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022F49E91A10>]}
[0m14:56:03.712259 [debug] [MainThread]: On master: ROLLBACK
[0m14:56:03.713258 [debug] [MainThread]: Using postgres connection "master"
[0m14:56:03.714257 [debug] [MainThread]: On master: BEGIN
[0m14:56:03.716164 [debug] [MainThread]: SQL status: BEGIN in 0.002 seconds
[0m14:56:03.717188 [debug] [MainThread]: On master: COMMIT
[0m14:56:03.717188 [debug] [MainThread]: Using postgres connection "master"
[0m14:56:03.717188 [debug] [MainThread]: On master: COMMIT
[0m14:56:03.718166 [debug] [MainThread]: SQL status: COMMIT in 0.001 seconds
[0m14:56:03.719165 [debug] [MainThread]: On master: Close
[0m14:56:03.720162 [debug] [Thread-1 (]: Began running node model.my_dbt_project.raw.data
[0m14:56:03.721162 [info ] [Thread-1 (]: 1 of 1 START sql table model public.raw.data ................................... [RUN]
[0m14:56:03.722162 [debug] [Thread-1 (]: Acquiring new postgres connection 'model.my_dbt_project.raw.data'
[0m14:56:03.722162 [debug] [Thread-1 (]: Began compiling node model.my_dbt_project.raw.data
[0m14:56:03.727161 [debug] [Thread-1 (]: Writing injected SQL for node "model.my_dbt_project.raw.data"
[0m14:56:03.728162 [debug] [Thread-1 (]: Began executing node model.my_dbt_project.raw.data
[0m14:56:03.758038 [debug] [Thread-1 (]: Writing runtime sql for node "model.my_dbt_project.raw.data"
[0m14:56:03.760044 [debug] [Thread-1 (]: Using postgres connection "model.my_dbt_project.raw.data"
[0m14:56:03.760044 [debug] [Thread-1 (]: On model.my_dbt_project.raw.data: BEGIN
[0m14:56:03.761044 [debug] [Thread-1 (]: Opening a new connection, currently in state init
[0m14:56:03.777104 [debug] [Thread-1 (]: SQL status: BEGIN in 0.017 seconds
[0m14:56:03.778105 [debug] [Thread-1 (]: Using postgres connection "model.my_dbt_project.raw.data"
[0m14:56:03.778105 [debug] [Thread-1 (]: On model.my_dbt_project.raw.data: /* {"app": "dbt", "dbt_version": "1.9.2", "profile_name": "default", "target_name": "dev", "node_id": "model.my_dbt_project.raw.data"} */

  
    

  create  table "mydatabase"."public"."raw.data__dbt_tmp"
  
  
    as
  
  (
    create  table "mydatabase"."voo"."raw.data__dbt_tmp"
  
  
    as
  
  (
    -- Modelo simples para visualizar dados brutos

select * from voo
  );
  );
  
[0m14:56:03.780103 [debug] [Thread-1 (]: Postgres adapter: Postgres error: syntax error at or near "create"
LINE 12:     create  table "mydatabase"."voo"."raw.data__dbt_tmp"
             ^

[0m14:56:03.780103 [debug] [Thread-1 (]: On model.my_dbt_project.raw.data: ROLLBACK
[0m14:56:03.781105 [debug] [Thread-1 (]: On model.my_dbt_project.raw.data: Close
[0m14:56:03.785104 [debug] [Thread-1 (]: Database Error in model raw.data (C:/Users/henrique.soares/Desktop/DataGlowUp/models\raw.data.sql)
  syntax error at or near "create"
  LINE 12:     create  table "mydatabase"."voo"."raw.data__dbt_tmp"
               ^
  compiled code at C:/Users/henrique.soares/Desktop/DataGlowUp/models\raw.data.sql
[0m14:56:03.786103 [debug] [Thread-1 (]: Sending event: {'category': 'dbt', 'action': 'run_model', 'label': '174ffd03-6341-42ae-8889-010442b8d046', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022F449CFF10>]}
[0m14:56:03.787120 [error] [Thread-1 (]: 1 of 1 ERROR creating sql table model public.raw.data .......................... [[31mERROR[0m in 0.06s]
[0m14:56:03.788104 [debug] [Thread-1 (]: Finished running node model.my_dbt_project.raw.data
[0m14:56:03.788104 [debug] [Thread-4 (]: Marking all children of 'model.my_dbt_project.raw.data' to be skipped because of status 'error'.  Reason: Database Error in model raw.data (C:/Users/henrique.soares/Desktop/DataGlowUp/models\raw.data.sql)
  syntax error at or near "create"
  LINE 12:     create  table "mydatabase"."voo"."raw.data__dbt_tmp"
               ^
  compiled code at C:/Users/henrique.soares/Desktop/DataGlowUp/models\raw.data.sql.
[0m14:56:03.790105 [debug] [MainThread]: Using postgres connection "master"
[0m14:56:03.790105 [debug] [MainThread]: On master: BEGIN
[0m14:56:03.790105 [debug] [MainThread]: Opening a new connection, currently in state closed
[0m14:56:03.817910 [debug] [MainThread]: SQL status: BEGIN in 0.028 seconds
[0m14:56:03.818911 [debug] [MainThread]: On master: COMMIT
[0m14:56:03.819913 [debug] [MainThread]: Using postgres connection "master"
[0m14:56:03.819913 [debug] [MainThread]: On master: COMMIT
[0m14:56:03.820909 [debug] [MainThread]: SQL status: COMMIT in 0.001 seconds
[0m14:56:03.821909 [debug] [MainThread]: On master: Close
[0m14:56:03.821909 [debug] [MainThread]: Connection 'master' was properly closed.
[0m14:56:03.822911 [debug] [MainThread]: Connection 'list_mydatabase' was properly closed.
[0m14:56:03.822911 [debug] [MainThread]: Connection 'list_mydatabase_public' was properly closed.
[0m14:56:03.823918 [debug] [MainThread]: Connection 'model.my_dbt_project.raw.data' was properly closed.
[0m14:56:03.823918 [info ] [MainThread]: 
[0m14:56:03.824910 [info ] [MainThread]: Finished running 1 table model in 0 hours 0 minutes and 0.33 seconds (0.33s).
[0m14:56:03.824910 [debug] [MainThread]: Command end result
[0m14:56:03.839955 [debug] [MainThread]: Wrote artifact WritableManifest to C:\Users\henrique.soares\Desktop\DataGlowUp\target\manifest.json
[0m14:56:03.841957 [debug] [MainThread]: Wrote artifact SemanticManifest to C:\Users\henrique.soares\Desktop\DataGlowUp\target\semantic_manifest.json
[0m14:56:03.845956 [debug] [MainThread]: Wrote artifact RunExecutionResult to C:\Users\henrique.soares\Desktop\DataGlowUp\target\run_results.json
[0m14:56:03.846956 [info ] [MainThread]: 
[0m14:56:03.847956 [info ] [MainThread]: [31mCompleted with 1 error, 0 partial successes, and 0 warnings:[0m
[0m14:56:03.847956 [info ] [MainThread]: 
[0m14:56:03.848956 [error] [MainThread]:   Database Error in model raw.data (C:/Users/henrique.soares/Desktop/DataGlowUp/models\raw.data.sql)
  syntax error at or near "create"
  LINE 12:     create  table "mydatabase"."voo"."raw.data__dbt_tmp"
               ^
  compiled code at C:/Users/henrique.soares/Desktop/DataGlowUp/models\raw.data.sql
[0m14:56:03.849956 [info ] [MainThread]: 
[0m14:56:03.850958 [info ] [MainThread]: Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
[0m14:56:03.852959 [debug] [MainThread]: Command `dbt run` failed at 14:56:03.851962 after 1.10 seconds
[0m14:56:03.852959 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022F43C0AA50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022F43C8B850>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022F43C8B890>]}
[0m14:56:03.853956 [debug] [MainThread]: Flushing usage events
[0m14:56:04.565676 [debug] [MainThread]: An error was encountered while trying to flush usage events
